languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Carl Newton"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Carl Newton"
  headline = "Web Developer"
  links = [
    { github = "https://github.com/carlnewton" },
    { linkedin = "https://www.linkedin.com/in/carlnewton" },
    { mastodon = "https://mastodon.world/@carlnewton" },
  ]
